name: imagecom
favicon: null
layout_spectrum: 0.6513698576018214
typography_spectrum: 0.48595301783643663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8848467832431197
  lightness: 0.8518746613990515
  saturation: 0.42475795466452837
  rhythmicContrast: 0.5782917253673077
purpose: []
